### ISSUE TITLE
New feature: display of image/picture

### ISSUE THREAD

**Issue by jbelien** [RobinLinde/equalstreetnames-groningen#1]
Hello @RobinLinde ,

Just wanted to let you know that there is now the image/picture displayed in the popup.
It uses Wikidata `P18` (image) property: https://www.wikidata.org/wiki/Property:P18

Next time you run `composer update-data -- --city=groningen` that field will be added to the GeoJSON files and images will be displayed.

Let me know if you have any question!

![image](https://user-images.githubusercontent.com/1150563/93020054-663ae480-f5db-11ea-96fd-7b089baf2beb.png)

**Comment by RobinLinde** [comment]
Looks good!

![image](https://user-images.githubusercontent.com/1395345/93023667-d3a54000-f5f0-11ea-8cca-d12f1878adca.png)

**Comment by RobinLinde** [comment]
Opened pull request https://github.com/openknowledgebe/equalstreetnames/pull/82
